version: "3.9"
services:
  kompetenz_center:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - sigma_shared_network
#    ports:
#      - 12001:2001
    environment:
      NODE_ENV: production
networks:
  sigma_shared_network:
    external: true
    name: sigma_shared_network