version: "3.9"
services:
  nginx-react:
    container_name: kompentenz_center
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
    environment:
      NODE_ENV: production